import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        alignItems: 'center',
        flex: 1,
        justifyContent: 'center',
        marginHorizontal: 20,
        marginVertical: 10,
        padding: 10,
    },
    containerForm: {
        alignItems: 'center',
        flex: 1,
        justifyContent: 'center',
        marginHorizontal: 20,
        marginVertical: 5,
        padding: 5,
    },
    title: {
        fontSize: 26,
        paddingVertical: 12,
        paddingHorizontal: 10,
        fontWeight: 'bold',
        color: 'white',
        backgroundColor: '#229adf',
        borderRadius: 10,
        textAlign: 'center',
        marginVertical: 20,
        elevation: 3,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
    },
    image: {
        width: 220,
        height: 220,
        marginVertical: 50,
    },
    button: {
        marginTop: 20,
        width: 90,
        height: 60,
        backgroundColor: '#229adfff',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 10,
        marginRight: 10
    },
    textButton: {
        color: 'white',
        fontSize: 17,
        fontWeight: 'bold'
    },
    input: {
        height: 45,
        marginVertical: 10,
        marginHorizontal: 20,
        borderWidth: 1,
        borderColor: '#ccc',
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 10,
        color: 'black',
        backgroundColor: '#f9f9f9',

        fontSize: 16,
    },
    textInputs: {
        fontSize: 18,
        color: '#333',
        marginTop: 8,
        marginHorizontal: 20,
        fontWeight: '500',
    },
    titleForm: {
        fontSize: 26,
        paddingVertical: 12,
        paddingHorizontal: 10,
        fontWeight: 'bold',
        color: 'white',
        backgroundColor: '#229adf',
        borderRadius: 10,
        textAlign: 'center',
        marginVertical: 20,
        elevation: 3,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
    },
    textResult: {
        fontSize: 22,
        color: '#1a1a1a',
        marginTop: 15,
        textAlign: 'center',
        fontWeight: '600',
    }
})